### ISSUE TITLE
Ugly highlighting in SCSS

### ISSUE THREAD

**Issue by kodekrendel** [hudochenkov/Syntax-highlighting-for-PostCSS#17]
Hi. I to get rid of this kind of highlighting? 

![urod](https://cloud.githubusercontent.com/assets/26049747/26672304/b01a4346-4686-11e7-95c2-06c6c72753a3.png)

**Comment by hudochenkov** [comment]
I don't know. It's syntax highlighting for _PostCSS_ repository, not for SCSS.

**Comment by kodekrendel** [comment]
May be any custom fixes? Can't believe nobody have the same issue.
What you propose - using .postcss files?

**Comment by hudochenkov** [comment]
As I see it's a html file. I don't know what syntax Sublime Text is using at the moment. Probably it's just CSS.

If you use a separate file for styles and set your syntax highlighting to PostCSS, then you'll see no problems.

**Comment by kodekrendel** [comment]
It's .vue file, but I have the same result in separate .scss file anyway. Same error highlighting.

**Comment by kodekrendel** [comment]
> set your syntax highlighting to PostCSS, then you'll see no problems.
The problem is, my current file using Vue Component highlighting. So I should fixed something in it, probably. Have no idea how to make it.

**Comment by hudochenkov** [comment]
![image](https://cloud.githubusercontent.com/assets/654597/26674180/2d1a3ed2-46c8-11e7-8927-784194a14189.png)

I see no problems. I don't know how to enable one syntax highlighting inside another one. Probably vue-syntax-highlight developers have an idea.

I'm closing this issue, because it's not related to PostCSS syntax highlighting.
